### ISSUE TITLE
Nothing is changed

### ISSUE THREAD

**Issue by JohnReedLOL** [Montaron/Slitherio-Plugin#4]
I downloaded it for chrome. It's listed in my TamperMonkey ![here](http://s32.postimg.org/mytd61qqd/plugin.png)

The thing is, my slither looks EXACTLY the same.

No ip/port.

**Comment by JohnReedLOL** [comment]
![screenshot](http://s32.postimg.org/xtqfip9qt/slither.png)

**Comment by JohnReedLOL** [comment]
![screenshot2](http://s32.postimg.org/6lg9picnp/slither2.png)

**Comment by JohnReedLOL** [comment]
As you can see, the slitherio plugin is on and the Slitheriomods plugin is off (upper right)

**Comment by hchagen** [comment]
I'll have a look at it. Sorry about the late response, I was at a convention in Berlin.

**Comment by hchagen** [comment]
Unfortunately, I am unable to recreate the issue you're experiencing. I'm running tampermonkey in chrome on Ubuntu 16.04 with unity, and here it just works out of the box. Are you still experiencing the issue?

**Comment by JohnReedLOL** [comment]
I'll tell you what. I will record my screen installing tampermonkey in Chrome, going to your GitHub, installing your tampermonkey script, and then playing slither.io . There will be a link with the screen record posted here as a reply by tomorrow.

-------- Original message --------
From: HCHagen
Date:05/12/2016 3:39 AM (GMT-05:00)
To: Montaron/Slitherio-Plugin
Cc: "Reed,John-Michael" ,Author
Subject: Re: [Montaron/Slitherio-Plugin] Nothing is changed (#4)

Unfortunately, I am unable to recreate the issue you're experiencing. I'm running tampermonkey in chrome on Ubumtu 16.04 with unity, and here it just works out of the box. Are you still experiencing the issue?

##

**Comment by JohnReedLOL** [comment]
@HCHagen - https://youtu.be/m2m1GRk2Iqs (1080p, 60fps)

**Comment by phpdave11** [comment]
I also have this issue on Mac OS X / Chrome.  Nothing looks different.

Worked in Firefox with Greasemonkey, though.  However, after I try to join with server ip:port, I get these errors in the Firefox Console (I attempted to join 206.191.155.104:446 after playing on it once successfully):

```
Firefox can't establish a connection to the server at ws://206.191.155.104:446/slither. game9c8ns.js:198:316
The connection to ws://206.191.155.104:446/slither was interrupted while the page was loading. game9c8ns.js:198:316
Firefox can't establish a connection to the server at ws://206.191.155.104:446/slither. game9c8ns.js:198:316
The connection to ws://206.191.155.104:446/slither was interrupted while the page was loading.
```

**Comment by ghost** [comment]
Hmm. I still havent been able to reproduce this error on any of my own rigs. It could be caused by the script referencing the forceserver-function (which is actually part of the original slitherio script), without accessing it using the unsafeWindow-prefix supported by Greasemonkey, but that's just guesswork.

If you want to, Dave, you can look into it and merge the fix to the master branch if you figure it out? I can be available to help you, too :).
